package application;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;




public class signupController {
	@FXML
	private TextField facultyname;
	@FXML
	private TextField facultyaddress;
	@FXML
	private TextField facultyemail;
	@FXML
	private PasswordField facultypassword;
	@FXML
	private TextField adminemail;
	@FXML
	private PasswordField adminpassword;
	@FXML
	private TextField adminaddress;
	@FXML
	private TextField adminname;
	
	Registration registration= new Registration();
	

	
	public signupController(Registration reg) {
	    registration = reg;
	}
	
	public signupController() {
	    
	}
	
	public void test() {
		
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void facultySignup(ActionEvent event) {
		
		String n= facultyname.getText();
		String a= facultyaddress.getText();
		String e= facultyemail.getText();
		String p=facultypassword.getText();
		registration.registerFaculty(n, p, a, e);
	}
	
	@FXML
	public void adminSignup(ActionEvent event) {
		
		String n= adminname.getText();
		String a= adminaddress.getText();
		String e= adminemail.getText();
		String p= adminpassword.getText();
		registration.registerAdmin(n, p, a, e);
		
		
		
	}
	// Event Listener on Button.onAction
	@FXML
	public void login2(ActionEvent event) {
		// TODO Autogenerated
	}
	
	
	
	 public void loginScreen(ActionEvent event) throws IOException {
	    	
	    	Main m= new Main();
	    	m.changeScene("login.fxml");
	    }
}
